Update com.apple.extensiblesso.plist
ProfileManifests/ProfileManifests pull request #674
Opened 2024-05-21 18:35 UTC by bgatestmg

This should fix the crashing issue for this payload. at least in my localized testing it has.

2024-05-22 00:17 UTC, homebysix commented
Please make this update upstream. See the readme for details.

2024-09-02 17:29 UTC, kevinmcox approved these changes
Confirmed this fixes the crash with ProfilesCreator 0.3.3

2024-09-02 17:34 UTC, kevinmcox requested changes

2024-09-02 17:34 UTC, kevinmcox commented on Manifests/ManifestsApple/com.apple.extensiblesso.plist
>  	<integer>6</integer>
Can you bump the `pfm_version` to 7 please.

2024-09-02 21:08 UTC, relgit commented
Isn't this an as-is copy of the DigiDNA fork manifest?

I'm glad it works and we've never kept our manifest work to ourselves, but there are too many changes to tell us what actually makes the difference.

Could you perhaps do some elimination?

2025-01-11 21:32 UTC, kevinmcox commented
The latest release of Profile Creator no longer crashes when this payload is loaded.

2025-01-11 21:32 UTC, closed without merging