Add Okta Verify
ProfileManifests/ProfileManifests pull request #737
Opened 2024-12-26 03:59 UTC by Fgeronimo

Addresses https://github.com/ProfileManifests/ProfileManifests/issues/669

[Documentation](https://help.okta.com/oie/en-us/content/topics/identity-engine/devices/managed-app-configs-macos.htm)

I have a couple of questions:

- [This has been asked before](https://macadmins.slack.com/archives/CH9LT65U6/p1678477634031969), and I didn't address it yet. How should I proceed? Separate manifest files or something else?
- I'm confused by the documentation. Should [OktaVerify.Plugins](https://help.okta.com/oie/en-us/content/topics/identity-engine/devices/managed-app-configs-macos.htm#OktaVeri4) be included in this manifest? Should it be in the `com.crowdstrike.zta` preference domain?
- Regarding the [Device Health Option](https://help.okta.com/oie/en-us/content/topics/identity-engine/devices/managed-app-configs-macos.htm#OktaVeri) preference key, I'm unsure if it will work as it expects values separated by semicolons. I’d appreciate it if anyone could test this to see if it applies correctly.
```
<key>OktaVerify.DeviceHealthOptions</key>
<string>HideDiskEncryption;HideBiometrics</string>
```

I appreciate any assistance you can provide. Thank you!

2024-12-28 22:38 UTC, kevinmcox commented
Thanks for the submission, Okta sure doesn't want to make this easy.

> I'm confused by the documentation. Should [OktaVerify.Plugins](https://help.okta.com/oie/en-us/content/topics/identity-engine/devices/managed-app-configs-macos.htm#OktaVeri4) be included in this manifest? Should it be in the com.crowdstrike.zta preference domain?

I think this should be in the Okta preference domain based on reading the documentation.

I want to hear what @relgit thinks about all the other questions.

2025-01-06 11:28 UTC, relgit commented
@kevinmcox is right, but I don't think that we'd be able to fully support the `OktaVerify.Plugins` key in the manifest because of its highly unusual data structure.

If I understand it correctly, besides the array of bundle IDs you also need to insert custom-named keys at the root of the dictionary. You could theoretically do that with a pair of `{{key}}` and `{{value}}` subkeys, but none of the profile editors support this at the root level.

Regarding the two separate domain strings, the best solution would be to have two manifests in tandem, with identical subkeys but different domains and meta.

In the discussion you linked, AP is probably referring to `pfm_value_copy`, which may provide the functionality that you are looking for but I don't know if it works across payloads, and it is only currently supported in ProfileCreator.

Cheers!

2025-01-06 15:38 UTC, Fgeronimo commented
Thank you both for the help and clarification @kevinmcox @relgit

> If I understand it correctly, besides the array of bundle IDs you also need to insert custom-named keys at the root of the dictionary. You could theoretically do that with a pair of {{key}} and {{value}} subkeys, but none of the profile editors support this at the root level.

Good catch! I just tested this by downloading Okta Verify from App Store and exporting a profile with the following settings in the profile installed locally on my system (EnrollmentOptions/OrgURL/ReportDiagnostics/LaunchOptions) and Okta Verify took the settings applied in the profile. I am not an Okta customer so I can't test DeviceHealth (it won't work in it's current state).

> Regarding the two separate domain strings, the best solution would be to have two manifests in tandem, with identical subkeys but different domains and meta.

Will work on and update once completed.

> In the discussion you linked, AP is probably referring to pfm_value_copy, which may provide the functionality that you are looking for but I don't know if it works across payloads, and it is only currently supported in ProfileCreator.

From what I understand from the docs, this does not span manifests

2025-01-17 11:10 UTC, relgit requested changes
Looks like the manifests ended up not being identical in their subkeys. For example, `com.okta.mobile.plist `is missing `OktaVerify.UserPrincipalName` – why is that?

Also, they both lack a `PayloadOrganization` subkey.

2025-01-17 19:28 UTC, Fgeronimo commented
> Looks like the manifests ended up not being identical in their subkeys. For example, `com.okta.mobile.plist `is missing `OktaVerify.UserPrincipalName` – why is that?

@relgit I noticed that for `OktaVerify.UserPrincipalName`, I didn't see it referenced in the [docs](https://help.okta.com/oie/en-us/content/topics/identity-engine/devices/managed-app-configs-macos.htm). However, there is reference [here](https://help.okta.com/oie/en-us/content/topics/oda/macos-pw-sync/configure-macos-password-sync-policies.htm) as an optional key to be added in both manifests. When I tested this, `OktaVerify.UserPrincipalName` doesn't apply to Okta Verify, only Desktop Password Sync (from what I can see in testing). I also don't have strong feelings to leave UserPrincipleName out in `com.okta.mobile.plist` so if you want it in, I can do that.

> Also, they both lack a PayloadOrganization subkey.

Corrected in https://github.com/ProfileManifests/ProfileManifests/pull/737/commits/b9debda90dabbf0f4b8d881b7c0649808e442901

2025-02-03 18:19 UTC, Fgeronimo commented
Following up any other concerns here with this PR @relgit?

2025-02-18 13:19 UTC, relgit requested changes

2025-02-18 13:19 UTC, relgit commented on Manifests/ManagedPreferencesApplications/com.okta.mobile.auth-service-extension.plist
> +			<string>OktaVerify.UserPrincipalName</string>
Looks like this instance of `OktaVerify.UserPrincipalName` is a duplicate.

You can remove either this or the other one, depending on what order you think the field should appear in. If you remove this one, please remember to move its counterpart in the other manifest to match.

2025-02-20 00:39 UTC, Fgeronimo commented on Manifests/ManagedPreferencesApplications/com.okta.mobile.auth-service-extension.plist
> +			<string>OktaVerify.UserPrincipalName</string>
Apologies corrected in https://github.com/ProfileManifests/ProfileManifests/pull/737/commits/f025de28e318666a1fa7b9f7cd969d0768a9a360
OktaVerify.UserPrincipalName exists in other manifest. Appreciate the help here!

2025-02-20 08:47 UTC, relgit approved these changes

2025-02-20 08:47 UTC, merged